= Miks ees alotit? -- tai Miks hait lääkikseen, osa II

Toi otsikon kysymys jaksaa aina lämmittää mieltä. Ja on se pari kertaa tuntunu rehellisesti pahaltakin. Mut ihan asiallinen kysymys se on. Koen olevani köyteni päässä sen suhteen miten eräs kanssaopiskelija jaksaa aiheesta kuulla, joten koitetaan hoitaa tää pois alta.

Luotin menneisyyden itseeni. :: Kai mulla joku syy täyty olla. Ja varmaan se oli ihan hyvä syy, jos kerran jaksoin itteni sisälle lukee?

Vika tsäänssi. :: En ois oikein (hyvällä omallatunnolla) pystyny lykkäämään enää aloittamista. En tiedä miten tuo 2013 lukuvuoden poissa- saati läsnäolevaksi-ilmoittautumattajättäminen vaikutti tutkinnonsuoritusoikeuteen -- enkä uskalla kysyä, koska nyt tulkinta näyttäis olevan mulle edullinen -- mutta nykyään mikään ei oo ikuista. Lisäksi työelämän suhteen aloin olla sen verran syvissä vesissä et seuraavaksi ois pitäny opetella uimaan. Sit tää maaelämä ois onnistunu varmaan vielä huonommin.

Accidents come in threes. :: Ajattelin hoitaa ton kolmannen pois alta ennen kuin sattuu mitään pahempaa. Valehtelisin jos sanoisin, ettei muilla elämänmuutoksilla ollut vaikutusta siihen, miten helppoa aloittaminen oli.


Kuten oon jo sanonu, en kadu et alotin.

 The best of you
 I like more than you think

https://gist.github.com/sakkemo/85bf2637aba0b3c041dd[(One for the Shoeshine man.)]


''''

Hauskinta opinnoissa tähän mennessä on ollut kun päädyin kääntämään Rubya jotta saan hyväksilukuanomukseni Asciidocista PDF:ksi. Et en sit tiiä.

"Miks lopettasin?" taitaa jäädä seuraavaan postaukseen.