= 2 juttuu

// Tartuin tsäänssiin ja _klubille_ suuntaamisen sijaan

Nautittiin aiemmin täl viikolla terassikeleistä (heh) ja siinä jutellessa tulin maininneeksi että en oo ikinä kokenut kuuluvani mihinkään viiteryhmään ja et oon pitäny sitä jonkinlaisena ongelmana. Ihan validina kritiikkinä tälle esitettiin et

. eipä sitä kukaan välttämättä hirveen vahvasti koe kuuluvansa mihinkään
. on mul kuitenki jotain ollu.

Joka tapauksessa tälle asialle ei oo sellasta ratkasua varmaan tulossa et löytäsin itelleni jonku viiteryhmän johon vahvasti kokisin kuuluvani. Lääkiksessä oisin kuitenki toinen jalka ulkona ovesta ja lääkärinä varmaan insinööri. Ja insinöörinä jotain muuta. Mut ajattelin yrittää miettii et mitä oon ja yrittää olla parempi niissä jutuissa missä oon hyvä ja skarpata niissä missä en oo ja saada selvyys et mitä haluun ja oon. Ois hienoo jos ois vahva identiteetti ja sit (kuvittelis et) tekis sen kans konsistenttei päätöksiä ja vois olla varma jostain.

Ehdin jo unohtaa et mikä se toinen juttu on, mut kirjotetaan nyt vaikka siitä et koen jotenki vahvasti että en tykkää jutuista joista monet tykkää ja tykkään monista jutuista joista useimmat ei ja monet jutut on mulle ihan sama joilla useimmille on väliä. Olin jo matkalla _klubille_ mut sit meninki töikaverin ruokaseuraks ku tarjoutu tsäänssi ja juteltiin ja käveltiin ja sit kävelin yksin himaan ja mietin matkalla et jos kirjottas.