= Miks ees alotit? -- tai Miks hait lääkikseen, osa II

Toi otsikon kysymys jaksaa aina lämmittää mieltä. Ja on se pari kertaa tuntunu rehellisesti pahaltakin. Mut ihan asiallinen kysymys se on. Koen olevani köyteni päässä sen suhteen miten eräs kanssaopiskelija jaksaa aiheesta kuulla, joten koitetaan hoitaa tää pois alta.

Luotin :: menneisyyden itseeni. Kai mulla joku syy täyty olla. Ja varmaan se oli ihan hyvä syy, jos kerran jaksoin itteni sisälle lukee?

Vika tsäänssi. :: En ois oikein (hyvällä omallatunnolla) pystyny lykkäämään enää aloittamista. En tiedä miten tuo 2013 lukuvuoden poissa- saati läsnäolevaksi-ilmoittautumattajättäminen vaikutti tutkinnonsuoritusoikeuteen -- enkä uskalla kysyä, koska nyt tulkinta näyttäis olevan mulle edullinen -- mutta nykyään mikään ei oo ikuista. Lisäksi työelämän suhteen aloin olla sen verran syvissä vesissä et seuraavaksi ois pitäny opetella uimaan. Sit tää maaelämä ois onnistunu varmaan vielä huonommin.

Accidents :: come in threes. Ajattelin hoitaa ton kolmannen pois alta ennen kuin sattuu mitään pahempaa. Valehtelisin jos sanoisin, ettei muilla elämänmuutoksilla ollut vaikutusta siihen, miten helppoa aloittaminen oli.

http://www.hs.fi/ura/a1305973443078[Boreout.] :: Sitä ei kuulemma juuri esiinny lääkärin duunissa.

Työajat, :: työn varmuus ja palkka. Ajattelin et ainakin alkupäässä mun insinööriuraa vähemmän kuin viiden päivän viikkotyöajat taitaa olla vielä aika harvinaisia. Mulle riittäis vähempikin. Lisäks en välttämättä oo maailman kunnianhimoisin, ja lääkärin duunissa saattasin pärjätä rahallisesti ihan mukavasti tästä huolimatta.


Kuten oon jo sanonu, en kadu et alotin.


''''

Hauskinta opinnoissa tähän mennessä on ollut kun päädyin kääntämään Rubya jotta saan hyväksilukuanomukseni Asciidocista PDF:ksi. Et en sit tiiä.

"Miks lopettasin?" taitaa jäädä seuraavaan postaukseen.