= A & T
:hp-tags: frendit

Mun 2 vikaa opiskeluvuotta (ne jolloin kävin koulussa vielä, tätä vikaa ei oikein lasketa) oli sillai vittumaista aikaa, et lopulta mun pääainetta ei lukenu ainakaan samaan tahtiin kukaan. Niillä vikoilla kursseilla olikin sit tuttuja vaan satunnaisesti, ja suurin osa oli englanninkielisen maisteriohjelman tyyppejä jotka tuns jo toisensa. In hindsight, ois voinu tehä paremman effortin tutustua niihin mut sillon se tuntu jotenki vaikeelta ku oli jo omat kaveripiirit ja kouluki melkeen paketissa.

Niinpä se loppuopiskelu tuliki vedettyä läpi aika pienellä läsnäololla. Mut se ei oo tän postauksen pointti.

Jollain kurssilla, ilmeisesti syksyllä 2011footnote:[katoin logeista], oli sentään jotain tuttuja. Mikä lie erikoiskurssi oli kyseessä, mut siel oli herrat AM ja TV. Toki oltiin jossain määrin tuttuja jo etukäteen, mutta en muista et oltais vielä sillon nähty tai tehty mitään koulujuttujen ja opintoteutarointien ulkopuolella.

No, jollain Kvarkin lounaalla A ujosti (T--lta varmistaen?) kysy et pitäiskö. Ja päätös oli et juu kai miksei.

Näissä merkeissä on sit tullu tutustuttua paremmin moniin muihinkin tyyppeihin, käytyä Nykissä, Bosiksessa ja Berskassa, juostua Skotlannin nummilla ja paljon muutakin. Pienestä se elo, ja se mihin päätyy, on kii.

Vois jopa sanoo et _tuntuu hullulta._