= Miks hait lääkikseen? osa I

Viime viikolla tajusin, että se päätös ei oo ainoastaan et vieläkö tässä jaksaa opiskella 6 vuotta vaan myös haluunko tulevaisuudessa olla lääkäri. Ja otin ton aika raskaasti: en tiiä miks se tuntuu vaikeelta asialta eikä mahdollisuudelta.

Mut asiaan. Oikeastaan täs on 3 eri kysymystä:

. Miks hain lääkikseen?
. Miks jätin 2 kertaa aloittamatta?
. Miks aloitin nyt?

2012 taisin alkaa miettiä muita vaihtoehtoja ku sillon tuntu siltä että omat opinnot ei välttämättä nappaa, https://sakkemo.github.io/blog/2015/08/02/A-and-T.html[johtuen ehkä osaksi seuran puutteesta eikä varsinaisesti opinnoista.] 

Sen lisäksi että en ollu varma noista opinnoista, en myöskään ollu varma et tietotyöläisyys on mua varten. Tai pelkästään se, et se on lukupäätä ja kohtalaisen hyvä noissa jutuissa ei vielä tarkota et atk hommat tai Kalman-filtterit kiinnostais ja niitä ois syytä tehdä työkseen.footnote:[Myöhemmin on alkanu tuntua ehkä et mikäs niissäkään.] Sillon kiinnosti ehkä enemmän punttihommat ja miksei ihminenkin ja tosiaan joku muunlainen duuni kuin koneella istuminen.


Ekana tais olla mielessä fysioterapiakoulu ja jotain sellasia kattelenkin, mutta mut puhuttiin siitä ulos: se ei kuulemma kouluna oo välttämättä mikään best ja mielekkäin, tai en tiiä. Joku tällanen syy siinä oli. Jälkeenpäin ajatellen mut puhuttiin tosta aika helpolla ulos mut tiiä sit, ehkä se oli totta ja ystävän teko.

*Plan B.* Hain sit lääkikseen. 2012 en päässy, mut oon silti ylpeempi suorituksestani siinä kokeessa kuin 2013. Mut se on toinen tarina. 2012 se syy hakea oli toi ylläkuvattu, 2013 ehkä se et halus päästä sisään.

Jos oisin 2012 päässy sisään, oisin varmaan alottanu ja jättäny DI-hommat kanditutkintoon siltä erää. Mut en päässy, sit ehdin opiskella lisää, halusinki tehdä tutkinnon valmiiksi ja jätin alottamatta 2013 vaikka sillon sain paikan. 2013 olin täyspäiväsesti töissä ja tein dippaa ja sitä leikkii ois ollu vähä huono jättää kesken.

2014 olinki jo ekassa oikeessa työpaikassa (täyspäiväsessä vakiduunissa) enkä ees harkinnu alottamista. Ennemminki mielessä oli koissun otto ja asunnon osto. Eikä toi aloittaminen ollu mielessä ees vielä keväällä:

    2015-03-13 13:40:25     @sakkemo        pitäisköhän täs pitää viel se lääkispaikka
    [...]
    2015-03-30 15:06:41     @sakkemo        ainii lääkis
    2015-03-30 15:07:09     @sakkemo        pitäiskö maksaa joku lukukausi+myöhässäilmoomismaksu taas
    [...]
    2015-03-31 17:05:25     @sakkemo        oiskohan pitäny mennä sinne lääkikseen
    [...]
    2015-04-23 16:50:19     @sakkemo        jos pitäis ton lääkispaikanki vielä
    [...]
    2015-05-22 10:28:05     @sakkemo        http://www.iltasanomat.fi/tyoelama/art-1432181096961.html alottasko lääkikses
    2015-05-22 10:28:37     @sakkemo        pitäiski laittaa sinne mailia
    [...]
    2015-07-01 16:55:12     @sakkeom        vieläkö pitäis lääkispaikan
    [...]
    2015-07-01 17:13:56     @sakkeom        ottasko ton lääkispaikan ny viä

Heh.

Suuri osa tätä mun nykyistä ahdistusta on lienee just toi: oon 2 kertaa jättänyt aloittamatta koska asiat on ollu ihan hyvin ilmankin. Ei tää mulle mikään unelma oo, vaihtoehto vaan. Ja 2 kk sitten aloittaminen ei ollu vielä ees vaihtoehto.