= 140 penkistä

[.lead]
Tällaisena tää on ehkä vähän erikoinen tavoite tällä listalla.

Enemmän puntilla käyneet ehkä tajuu että tavoitteena tää ei oo hirveen mielekäs: Ei mikään huipputulos voimailussa, mutta tarpeeks iso et vaatii jo _salilla käymistä_ enemmän panostusta. Nokkelimmat ehkä hoksaa että toi 140 kiloa penkistä ei sinänsä oo se tavoite, vaan se on vaan sopivan lihapäinen ja siks -- ainakin musta -- hauska merkki siitä et jotain on tehty oikein muutenkin.footnote:[Vastareaktiona ainakin joskus vallinneelle elitismille, että penkkituloksella ei oo väliä. _Vain_ penkkituloksella on väliä.]

Lähtötilanne ei oo liene tuttu kellekään, mut 2014 helmi-maaliskuussa penkkasin 120 kg just because. Sen jälkeen sit oli kaikee muuta, niinku vaivoi, täyspäivänen vakiduuni, kiipihommia ja kesä, jonka aikana ja jälkeen fiksailtiin noita vaivoja sit vähä http://deansomerset.com/[Dean Somersetin] kans. Nyt taidan penkata juuri sen 100 kg, mut toisaalta oon vähemmän läski.

Koska metapuntti on äärimmäisen puuduttavaa

