= Älä ressaa

Disclaimer:: Suoritin just kolmesataa-ja-yksi opintopistettä, ja mulla on tutkinto ja työ alalta josta pidän ja jossa oon hyvä, mikä tehnee tästä huomattavasti helpompaa. Joku vois jopa kysyy et miks sit oot lääkiksessä, mut se on eri tarina.

Luin eilen jutun nimeltä http://www.huffingtonpost.com/kristen-lee-costa/your-mental-health-is-mor_b_8357368.html[Your mental health is more important than your grades]. Oleellinen ehkä jo otsikossa, mutta diggasin erityisesti pointeista

1. _Know that education is a privilege_, joka puhuttelee mua näin alanvaihtajana

ja

[start=3]
3. _Resist the bait of impostor syndrome_, joka puhuttelee mua näin alanvaihtajana.

En usko, et pääsen huomista tenttiä läpi, mutta en oo ottanut siitä stressiä. Aloin opiskella vasta viime viikolla (mikä vaati https://sakkemo.github.io/blog/2015/10/19/Koulujuttuja.html[yhden täysin penkin alle menneen PBL-session], https://sakkemo.github.io/blog/2015/10/11/A-week-in-review.html[identiteetin muutoksesta ylipääsyn] ja työssäkäynnin vähentämisen), joten voin elää ton kanssa.
++++
<blockquote class="instagram-media" data-instgrm-captioned data-instgrm-version="5" style=" background:#FFF; border:0; border-radius:3px; box-shadow:0 0 1px 0 rgba(0,0,0,0.5),0 1px 10px 0 rgba(0,0,0,0.15); margin: 1px; max-width:658px; padding:0; width:99.375%; width:-webkit-calc(100% - 2px); width:calc(100% - 2px);"><div style="padding:8px;"> <div style=" background:#F8F8F8; line-height:0; margin-top:40px; padding:50.0% 0; text-align:center; width:100%;"> <div style=" background:url(data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAACwAAAAsCAMAAAApWqozAAAAGFBMVEUiIiI9PT0eHh4gIB4hIBkcHBwcHBwcHBydr+JQAAAACHRSTlMABA4YHyQsM5jtaMwAAADfSURBVDjL7ZVBEgMhCAQBAf//42xcNbpAqakcM0ftUmFAAIBE81IqBJdS3lS6zs3bIpB9WED3YYXFPmHRfT8sgyrCP1x8uEUxLMzNWElFOYCV6mHWWwMzdPEKHlhLw7NWJqkHc4uIZphavDzA2JPzUDsBZziNae2S6owH8xPmX8G7zzgKEOPUoYHvGz1TBCxMkd3kwNVbU0gKHkx+iZILf77IofhrY1nYFnB/lQPb79drWOyJVa/DAvg9B/rLB4cC+Nqgdz/TvBbBnr6GBReqn/nRmDgaQEej7WhonozjF+Y2I/fZou/qAAAAAElFTkSuQmCC); display:block; height:44px; margin:0 auto -44px; position:relative; top:-22px; width:44px;"></div></div> <p style=" margin:8px 0 0 0; padding:0 4px;"> <a href="https://instagram.com/p/9DD5z-lzOB/" style=" color:#000; font-family:Arial,sans-serif; font-size:14px; font-style:normal; font-weight:normal; line-height:17px; text-decoration:none; word-wrap:break-word;" target="_blank">Eilisen jälkeen totesin et nyt on aika alottaa #opiskelu. Ostin vihkon, kynä mulla olikin jo.</a></p> <p style=" color:#c9c8cd; font-family:Arial,sans-serif; font-size:14px; line-height:17px; margin-bottom:0; margin-top:8px; overflow:hidden; padding:8px 0 7px; text-align:center; text-overflow:ellipsis; white-space:nowrap;">Kuva, jonka @scajanus julkaisi <time style=" font-family:Arial,sans-serif; font-size:14px; line-height:17px;" datetime="2015-10-20T05:33:54+00:00">19. 10ta 2015 klo 22.33 PDT</time></p></div></blockquote>
<script async defer src="//platform.instagram.com/en_US/embeds.js"></script>
++++

Sen sijaan että stressaisin huonosti menevää tenttiä, tai kyseenalaistaisin oman osaamiseni ja lääkiksessäoloni, oon ylpee siitä että oon alkanut tehdä oikeita asioita. Opiskelen säännöllisesti, mielestäni laadukkaasti ja oon oppinu asettamaan opiskelun (välillä) muiden asioiden edelle. Jos pitäisin tärkeänä menestymistä tässä tai tulevissa tenteissä, niitä stressais etukäteen ja jos -- syystä tai toisesta -- joku niistä menis huonosti, se vois olla kova paikka. Jos sen sijaan keskityn siihen, että tekeminen ja sen laatu on oleellista, voin olla tyytyväinen riippumatta minkään yksittäisen suorituksen tuloksesta. Tottakai on silti tärkeää tehdä oikeita asioita (ja riittävästi!), mutta ero on lähtökohdissa. En opiskele päästäkseni läpi tentistä, vaan koska _opiskelu on kivaa_ ja koska haluun tehdä sen hyvin.

Samasta syystä en enää edellisten opintojen loppuvaiheessa katsonut tenttiarkistosta vanhoja tenttejä: Luotin tekeväni oikeita asioita, ja vanhojen tenttien katsomisesta saatava hyöty ei tuntunut haittojen -- siitä mahdollisesti seuraavan itsensä kyseenalaistamisen -- arvoiselta.

---

En sano että tällainen ajattelutavan muutos on helppo juttu -- mulla siihen tais mennä vuosia, ja silti välillä saatan huomata stressaavani vääriä asioita -- mutta väitän että siihen pyrkiminen on sen arvoista.

Tietenkin se vaatii uskallusta ja luottoa siihen, että tekee oikeita asioita, mutta se riski jonka joutuu ottamaan on aika pieni hinta siitä että _ei tarvi juuri stressata_. En todellakaan jaksais opiskella 6 vuotta lisää, jos stressaisin jokaista koetta ja tenttiä.

Meinasin mä tästäkin tentistä stressata, mut sit totesin että _fuck it_. Stressaan mieluummin siitä, että saan opiskeltua laadukkaasti 4 tuntia päivässä.

---

Tää ei liity opiskeluun, mutta Jamie Lewis sanoo:

I’ve caught a lot of shit since I began writing about strength training and nutrition for being "angry", "mean", and most amusingly a "meathead". Clearly, the last one is pretty thoroughly off-base, though the first two are a bit closer to the mark. My writing style in indeed to be aggressive and offensive because aggressive and offensive writing are interesting. As for the anger I apparently direct at you, the reader, some of you have my intent wrong. I'm not berating you for being weak -- I’m berating my readers for believing that they should be weak. The reason I make such a big deal out of my humble strength training beginnings is because I was, for years, a chubby nerd. In the fifth grade, my nickname was "The Human Dictionary", and I was always picked for group projects but never for sports teams. As such, I was about as ill-suited for impressive physical strength as one could imagine. What I did have, however, was contempt for the opinions of other people that bordered on sociopathic and a belief in myself that could only have been construed as psychotic by my peers. Provided you have those two things, you can quite literally achieve any goal you set for yourself.


[quote, Henry Ford]
If you believe you can or if you believe you can’t... you’re right.

That's right -- the only thing standing in the way of your greatness is your lack of belief in yourself. Ellen Langer explained in her book Counterclockwise that the second step in the "psychology of possibility" is to try out new things without evaluating ourselves as we go along (Langer 16). The lack of evaluation of essential for exceeding who and what you are, and who you think you could be. If you push yourself to try new shit, things you thought were the sole purview of Superman and Dmitri Klokov, you could surprise yourself. The key, however, is to leave your judgment of yourself behind. You cannot walk into the gym wearing a powdered wig and swinging a gavel at every opportunity -- should you do so, you remove both the possibility for experimentation and any probability of greatness, because you'll be too fucking busy talking shit to yourself, convincing yourself that you're incapable and weak and useless as everyone around you to attack the fucking weights and be the human being you never thought you could be.


