= 2 juttuu

// Tartuin tsäänssiin ja _klubille_ suuntaamisen sijaan

Nautittiin aiemmin tällä viikolla terassikeleistä (heh) ja tulin maininneeksi että en oo ikinä kokenut kuuluvani mihinkään viiteryhmään ja et pidän sitä jonkinlaisena ongelmana. 

////
Ihan validina kritiikkinä tälle esitettiin et

. eipä sitä kukaan välttämättä hirveen vahvasti koe kuuluvansa
. on mul kuitenki jotain ollu.
////


.Esimerkiks,
****
Käyn jonkin verran kiipeemässä ja oon siinä jo ihan kohtalainen, mut en oikein tunne olevani _kiipeilijä_ tai haluakaan. En ymmärrä slangia, en omista mitään _kiipeilyvaatteita_ enkä kuulu mihinkään kerhoon. All-in-all, tykkään vaan käydä kiipeemässä ja kehittyy siinä. Mut en koe et oisin kiipeilijä.

Mun viha punttijutuista puhumista kohtaan kumpuu osaltaan siitä et en koe olevani mikään _punttijäbä_ vaik joskus on tullu treenattuaki ja kehityttyäkin ja voimanostossa kisattuakin.

Fiksipyöräilijänä en oo ollu mukana missään yksivaihdeympyröissä. Maantiepyöräilijänä oon aika hyvin välttäny pyöräilijäpiirit, vaikka parilla kimppalenkillä oonki käyny. Teekkariaktiivina urani päätty nopeesti sen jälkeen ku hallituspestini päättyi.
****

Näiden juttujen harrastaminen vois olla antoisampaa jos niissä ois enemmän mukana. Opiskelunkin ois voinu hoitaa jotenki muuten kuin pitämällä kurssien suoritusta välttämättömänä pahana et saa tutkinnon.

Eli ehkä täytyy kokeilla. Olla jossain enemmän mukana. Panostaa enemmän juttuihin joista pitää.

Mut kiipeilyhousut ajattelin silti jättää ostamatta.

////
Joka tapauksessa tälle asialle ei oo sellasta ratkasua varmaan tulossa et löytäsin itelleni jonku viiteryhmän johon vahvasti kokisin kuuluvani. Lääkiksessä oisin kuitenki toinen jalka ulkona ovesta ja lääkärinä varmaan insinööri. Ja insinöörinä jotain muuta. Mut ajattelin yrittää miettii et mitä oon ja yrittää olla parempi niissä jutuissa missä oon hyvä ja skarpata niissä missä en oo ja saada selvyys et mitä haluun ja oon. Ois hienoo jos ois vahva identiteetti ja sit (kuvittelis et) tekis sen kans konsistenttei päätöksiä ja vois olla varma jostain.
////


'''
Ehdin jo unohtaa et mikä se toinen juttu on, mut kirjotetaan nyt vaikka siitä et koen jotenki vahvasti että en tykkää jutuista joista monet tykkää ja tykkään monista jutuista joista useimmat ei ja monet jutut on mulle ihan sama joilla useimmille on väliä. Oli perjantai-ilta, olin jo matkalla _klubille_ mut sit meninki töikaverin ruokaseuraks ja juteltiin ja käveltiin ja sit kävelin yksin pari kilsaa himaan ja mietin matkalla et jos kirjottas jotain.