= Miks lopettasit?
:published_at: 2015-09-15

Tää saattaa kuulostaa monen mielestä väärältä, mut en toivo mitään muuta niin paljon kuin et voisin todeta et ei, tää ei kiinnosta mua ja en halua tätä. Mut sit mun elämä muuttuis kertaluokkaa helpommaks. Palaisin takas täyspäiväsiin töihin, reissaisin. Ehkä lähtisin ulkomaille. Aloittaisin uuden harrastuksen.

'''

Kuten sanottua, lääkäriys ei oo mulle mikään lapsuuden haave tai unelma-ammatti. Vaikka valmistuisin lääkäriksi, tuskin tekisin varsinaista lääkärinduunia ainakaan pelkästään. Voin siis tehdä (kuvitella tekeväni) valinnan lopettamisesta sen perusteella, tukeeko 6 vuoden opiskelu ja mahis tehdä lääkärihommia mun tavoitteita noin muuten.

Koska mikään niistä ei oo _olla lääkäri_, ei tän koulun läpäisy oo mikään edellytys millekään niistä. Niinpä oonki valmis jättämään tän kesken, esimerkiksi jos

* Näyttää siltä et opiskelu on helvetin tuskaista
* Työnteko samaan aikaan ei onnistu ja/tai säällinen toimeentulo on jotenki muuten hankalaa
* Lääkärin duuni vaikuttaa liian rankalta tai muuten mulle ei-sopivalta
* Suomessa menee kaikki päin helvettiä
* T-- ei palaakaan Suomeen
* Ulkomaat alkaa houkuttaa liikaa jostain muusta syystä
* Polvet ei kestä reissaamista laru-meikku-hima -kolmiossa
* Muu, mikä? Kai niit on.


Toisaalta tää ratkeis myös siltä jos tästä innostuis. Eilen tuntu ekaa kertaa siltä että ehkä tän vois tehdä loppuunkin.