= 2016

[,J--, Tietäen täysin että en ollu päässy yhdestäkään tentistä läpi.]
""
Miten on syksy menny?
""
[,]
""
Ihan hyvin, en oo päässy vielä yhdestäkään tentistä läpi.
""
[,Toimari]
""
Voidaan ostaa sulle tutkinto netistä jos tuut takas töihin.
""

___

Tää ois voinu olla vaikuttavampi, jos mulla ois ollu 3 tenttiä uusittavana 6.2. Luulen kuitenkin päässeeni yhdestä läpi, joten on vaan kax.


Jamie Lewis sanoo:
Every single setback you encounter in your life will become a boon if you approach it aggressively and positively.  This runs the gamut from work to relationships to lifting, and it's always true.  When I've found myself injured in the gym, I altered my technique and training to allow me to continue training hard, and my lifts have always improved as a result.  Sitting around moping like Eeyore off his meds is going to result in nothing more than continued failure and misery.  If you hit a wall in life, figure out a way to go over or through it without stopping to consider the wall's existence.  You can figure out how it got there after you get past it.  The important thing it to continue to progress to avoid stalling altogether and then backsliding.  